FROM lyft/gunicorn:70f2e13b372deb0dd3f45083836cc6121d0cea04
COPY requirements.txt /code/metadataproxy/requirements.txt
RUN /code/containers/python/pip-installer /code/metadataproxy/requirements.txt
COPY . /code/metadataproxy/
